identifier: lbiaj0s8p683j6v3
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: calc
homeFolder: C:\Users\rober\WebstormProjects\calc
distFolder: dist/calc
outDir: C:\Users\rober\WebstormProjects\calc\dist\static
handle404: ''
allowErrorCollect: true
